[package]
name = "llmqueue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.33"
pgmq = "0.26.1"
serde = "1.0.196"
serde_json = "1.0.113"
tokio = { version = "1.36.0", features=["rt"]}
